#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amartyne <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/03/21 21:05:45 by amartyne          #+#    #+#              #
#    Updated: 2018/03/23 15:07:51 by amartyne         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file
SRC = ft_display_file.c

all:
	gcc -o $(NAME) $(SRC)
clean:
	rm -f *.o
fclean: clean
	rm -f $(NAME)